### PR TITLE
Rails 4.2 and ActiveJob metrics

### PR DESCRIPTION
**Pull request by ChrisLundquist**
Tweaks for Rails 4.2.
This probably breaks rails 3 compatibility and would be best treated as a major version change.
It might be possible to support both Rails 3 and Rails 4, but would make the code a little more complicated. I'm also unsure on how it would extend to Rails 5.

### CODE REVIEW

**Comment by jnunemaker** [comment]
I dislike having different versions for different versions of rails, but perhaps that is ok since really there shouldn't be much maintenance for older versions. I have made a note to pull this down locally and kick the tires. Might be a week or so until I get time. Sorry I missed this originally.

**Comment by ChrisLundquist** [comment]
Sure things. Another approach would be to check against `RAILS_VERSION` or `Rails::VERSION::MAJOR` and friends. At the time, that approach didn't seem any more elegant.
Really I was after the ActiveJob metrics; I'll take any way that works.

**Comment by jnunemaker** [comment]
Haven't had time to review this yet, but still on my list.

**Comment by supagroova** [comment]
@ChrisLundquist nice work! I just discovered this gem today and almost immediately set about adding ActiveJob support, then I saw this PR... we'll probably use your fork until it gets approved :-)
 
:+1:

**Comment by bubenkoff** [comment]
@jnunemaker any chance for merging and releasing it?

**Comment by penso** [comment]
:+1:

**Comment by supagroova** [comment]
BTW, we've been using this in production for a month without issue.

**Comment by jnunemaker** [comment]
> BTW, we've been using this in production for a month without issue.

Yeah, the biggest thing I'm looking to fix before merging is I would like to try to do a backwards compatible fix to support rails 3 and maybe 5 going forward. Maybe that isn't possible.

**Comment by jnunemaker** [comment]
Released 0.4.0 for rails 4.2 only.

**Comment by jnunemaker** [comment]
Thanks! Should have just done this. Ah well.

**Comment by bubenkoff** [comment]
thanks a lot!

On 16 February 2016 at 17:07, John Nunemaker <notifications@github.com>
wrote:

> Thanks! Should have just done this. Ah well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jnunemaker/nunes/pull/18#issuecomment-184747644>.
>



-- 
Anatoly Bubenkov

**Comment by janxious** [comment]
:clap:

**Pull request merged**
